title: MEALTIME WITH MADDY
email: makyo@drab-makyo.com
description: > # this means to ignore newlines until "baseurl:"
  LOUD FOOD with MADISON SCOTT-CLARY
baseurl: ""
url: "http://mealtime.with.maddypa.ws"
twitter_username: loudfood
github_username:  makyo
